print("Hallo Welt", "Marvin", "Vorlesung", "Auto",sep=" | ")
print("----------", "------", "---------", "----",sep=" | ")
print("Hallo Welt", "Marvin", "Vorlesung", "Auto",sep=" | ")
print("Hallo Welt", "Marvin", "Vorlesung", "Auto",sep=" | ")
print("Hallo Welt", "Marvin", "Vorlesung", "Auto",sep=" | ")
# print(" Marvin")